name: "build"

on:
  workflow_dispatch:

jobs:
  build:
    uses: takutakahashi/github-actions/.github/workflows/ghcr.yaml@main
    with:
      path: .
      image: takutakahashi/tagging-server:${{ github.sha }}
    secrets: inherit

